version: "3.7"
services:
  app:
    build:
      args:
        user: kupi
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: kupi
    container_name: kupi-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - kupi

  db:
    image: mariadb:10.5
    container_name: kupi-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
    volumes:
      - db-volume:/var/lib/mysql
    networks:
      - kupi

  nginx:
    image: nginx:alpine
    container_name: kupi-nginx
    restart: unless-stopped
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - kupi

volumes:
  db-volume:

networks:
  kupi:
    driver: bridge