version: "3.7"
services:
  app:
    build:
      args:
        user: centos
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: kupi
    container_name: kupi-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - kupi

  live:
    build:
      args:
        user: centos
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    command: ["php", "artisan", "wc:live"]
    image: kupi
    container_name: kupi-live
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - kupi

  db:
    image: mariadb:10.5
    container_name: kupi-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
    volumes:
      - db-volume:/var/lib/mysql
    networks:
      - kupi

  nginx:
    image: nginx:alpine
    container_name: kupi-nginx
    restart: unless-stopped
    labels:
      - "traefik.http.routers.kupi-http.entrypoints=web"
      - "traefik.http.routers.kupi-http.rule=Host(`kupi.fr`)"
      - "traefik.http.routers.kupi-http.middlewares=kupi-https"
      - "traefik.http.middlewares.kupi-https.redirectscheme.scheme=https"
      - "traefik.http.routers.kupi.entrypoints=websecure"
      - "traefik.http.routers.kupi.rule=Host(`kupi.fr`)"
      - "traefik.http.routers.kupi.tls=true"
      - "traefik.http.routers.kupi.tls.certresolver=le"
      - "traefik.docker.network=kupi_kupi"
      - "traefik.port=80"
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - kupi

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - kupi

volumes:
  db-volume:

networks:
  kupi:
    driver: bridge
